name: hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare hassfest layout
        run: |
          mkdir -p custom_components/hondalink
          mv __init__.py api.py binary_sensor.py button.py config_flow.py const.py coordinator.py device_tracker.py entity.py lock.py manifest.json nhtsa.py sensor.py util.py custom_components/hondalink/
          mv brand translations icon.png logo.png custom_components/hondalink/
      - uses: home-assistant/actions/hassfest@master
